name: application_policies
label: 8. Create application policies to trigger RADIUS 2FA authentication events

description: Modify the GlobalProtect agent configuration to support authentication policy.

extends:

type: panos

labels:
  collection:
    - X509 Certificates

variables:
  - name: portal_name
    description: Name of the portal
    default: Portal-1
    type_hint: text


snippets:
    - name: auth_policy
      xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/global-protect
#      xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/global-protect/global-protect-portal/entry
      file: 0-auth_policy.xml