name: authenticationn_policies
label: 9. Create authentication policies to trigger RADIUS 2FA authentication events

description: Authentication policies define what apps will trigger an additional 2FA authentication event.

extends:

type: panos

labels:
  collection:
    - X509 Certificates

variables:
  - name: policy_name
    description: Name of the authentication policy
    default: MFA from test source
    type_hint: text
  - name: src_zone
    description: What is the source zone?
    default: L3-TRUST
    type_hint: text
  - name: dst_zone
    description: What is the destination zone?
    default: L3-UNTRUST
    type_hint: text
  - name: dst_ip_addr
    description: What is the destination IP address?
    default: 192.168.35.X
    type_hint: ip_address
  - name: policy_name
    description: Name of the authentication policy
    default: MFA from test source
    type_hint: text
  - name: auth_enforcer
    description: Name of the authentication object
    default: Duo_Radius-Proxy
    type_hint: text
  - name: src_user
    description: username/group of the source user
    default: any
    type_hint: text

snippets:
    - name: auth_policy
      xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/authentication/rules
      file: 0-auth_policy.xml